on:
  push:
    branches: [ master ]
  schedule:
  - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # this is needed to make force pushing retain history
        fetch-depth: 0
    - uses: Bogdanp/setup-racket@v1.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.0'
        packages: 'gregor'
    - run: make all
