on:
  push:
    branches: [ master ]
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # this is needed to make force pushing retain history
        fetch-depth: 0
    - run: make all
