on:
  push:
    branches: [ master ]
  schedule:
  - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # this is needed to make force pushing retain history
        fetch-depth: 0
    - run: |
        if ! command -v retry &> /dev/null; then \
          sh -c "curl https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && chmod +x /usr/local/bin/retry"; \
        fi
    - run: retry make all
