on:
  push:
    branches: [ master ]
  schedule:
  - cron:  '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # this is needed to make force pushing retain history
        fetch-depth: 0
    - name: Update Repo Readme
      run: |
        ruby hack/update_readme.rb
        ruby hack/commit.rb
